# Mikołaj Depta 328690

main:
	cargo build --release
	cp target/release/transport transport

clean:
	cargo clean
	rm -f template-1
	rm -f template-3
	rm -f template-4
	rm -f solution-1
	rm -f solution-3
	rm -f solution-4

distclean:
	cargo clean
	rm -f template-1
	rm -f template-3
	rm -f template-4
	rm -f solution-1
	rm -f solution-3
	rm -f solution-4